### ISSUE TITLE
Bug: Pdm install fail due to multidict dep

### ISSUE THREAD

**Issue by v3ss0n** [litestar-org/litestar-hello-world#10]
### Description

```
ERRORS:
add multidict failed:
Traceback (most recent call last):
File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/nozander/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/installers/synchronizers.py", line 282, in
install_candidate
self.manager.install(can)
File "/home/nozander/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/installers/manager.py", line 33, in install
prepared.build(),
^^^^^^^^^^^^^^^^
File "/home/nozander/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/models/candidates.py", line 418, in build
self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/nozander/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/builders/wheel.py", line 24, in build
filename = self._hook.build_wheel(out_dir, self.config_settings, metadata_directory)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/nozander/.local/share/pdm/venv/lib/python3.12/site-packages/pyproject_hooks/_impl.py", line 256, in
build_wheel
return self._call_hook(
^^^^^^^^^^^^^^^^
File "/home/nozander/.local/share/pdm/venv/lib/python3.12/site-packages/pyproject_hooks/_impl.py", line 392, in _call_hook
self._subprocess_runner(
File "/home/nozander/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/builders/base.py", line 255, in
subprocess_runner
return log_subprocessor(cmd, cwd, extra_environ=env)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/nozander/.local/share/pdm/venv/lib/python3.12/site-packages/pdm/builders/base.py", line 106, in
log_subprocessor
raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
multidict/_multidict.c:970:37: note: (near initialization for ‘_parser.initialized’)
multidict/_multidict.c:970:43: error: initialization of ‘const char *’ from incompatible pointer type ‘const char * const*’
[-Wincompatible-pointer-types]
970 |     static _PyArg_Parser _parser = {NULL, _keywords, "popall", 0};
|                                           ^~~~~~~~~
multidict/_multidict.c:970:43: note: (near initialization for ‘_parser.format’)
multidict/_multidict.c:970:54: error: initialization of ‘const char * const*’ from incompatible pointer type ‘char *’
[-Wincompatible-pointer-types]
970 |     static _PyArg_Parser _parser = {NULL, _keywords, "popall", 0};
|                                                      ^~~~~~~~
multidict/_multidict.c:970:54: note: (near initialization for ‘_parser.keywords’)
error: command '/usr/bin/gcc' failed with exit code 1

See /home/nozander/.local/state/pdm/log/pdm-install-i5_zseup.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
```

### Steps to reproduce

```bash
- Clone repo
- `pdm install`
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.4.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by Alc-Alc** [comment]
Thank you, I can confirm this is a bug
